---
name: Deploy to PyPI

on:
  workflow_call:
    inputs:
      build_docs:
        required: false
        type: boolean
        default: false
      deploy_docs:
        required: false
        type: boolean
        default: false

jobs:
  build_and_publish_pypi:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'statnett'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: build package
        run: uv build
      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1.10
        with:
          repository-url: https://test.pypi.org/legacy/
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1.10  # Use v1.10 https://github.com/pypa/twine/pull/1172
